name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: echo-event-name
        run:
          echo "🎉 The job was automatically triggered by a ${{
          github.event_name }} event."
      - id: echo-runner-info
        run:
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted
          by GitHub!"
      - id: echo-repo-info
        run:
          echo "🔎 The name of your branch is ${{ github.ref }} and your
          repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: echo-repo-cloned
        run:
          echo "💡 The ${{ github.repository }} repository has been cloned to
          the runner."
      - id: echo-workflow-ready
        run:
          echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        id: list-files
        run: |
          ls ${{ github.workspace }}
      - id: echo-job-status
        run: echo "🍏 This job's status is ${{ job.status }}."
  Upload-coverage-reports-to-Codecov:
    name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
